### ISSUE TITLE
JS Error on hosted-fields library

### ISSUE THREAD

**Issue by bcavenagh-foxtrot** [nathanstitt/react-braintree-fields#35]
We're getting an issue on our hosted fields that we aren't really sure how to solve. This TypeError is showing up pretty consistently in our monitoring but we have the Braintree library set up according to the documentation.
![Screen Shot 2022-02-10 at 1 46 50 PM](https://user-images.githubusercontent.com/93142880/153491617-3be14178-372a-47e3-9547-ca3f84fe33c9.png)

We think it might be related to this line: https://github.com/nathanstitt/react-braintree-fields/blob/19eb96c387c671c1e0e2b91079eb2c68606d0e41/src/field.jsx#L48 since that appears to be the only area where .push() is called in the repo. 

Have you encountered this error before? If so, is there a solution that you can share?

Thanks!

**Comment by nathanstitt** [comment]
Hm, no I haven't encountered any errors of that nature.  We run it with sentry monitoring and haven't seen any errors reported.

I doubt it's that line though because I can't see any way that `list` would be undefined, due it being created on the line above.

That is very puzzling though since I do not see any other uses of `push` anywhere in `hosted-fields` 

Lets leave this issue open for awhile in hopes that someone else has encountered it and can comment about it?

**Comment by bcavenagh-foxtrot** [comment]
![Screen Shot 2022-02-25 at 12 53 30 PM](https://user-images.githubusercontent.com/93142880/155771860-d4518788-7169-450c-b204-423a9a104d2b.png)

Looking further into this and found where in the minified file the error is being thrown. Line 275 here is what's causing the error. Not sure if you know how to fix it from here but going to continue digging into it to see if I can find some fix

**Comment by nathanstitt** [comment]
Hm, that is interesting.  I don't see any code like that in here, so I'm guessing that code is somewhere in the Braintree library. It seems to be expecting a JSON encoded string as the argument.   Maybe we're calling Braintree incorrectly somewhere and triggering this?  Are you able to obtain a stack trace for the call before this one?

**Comment by nathanstitt** [comment]
@bcavenagh-foxtrot I've just released a new version to fix a few other bugs.  Am curious if you also see any improvement?

**Comment by bcavenagh-foxtrot** [comment]
Yea after digging more, I do believe it's coming from the braintree-web library. The new version of react-braintree-fields didn't seem to fix it unfortunately

**Comment by bcavenagh-foxtrot** [comment]
Ahh it looks like it may have been caused by us having the "https://js.braintreegateway.com/web/3.8.0/js/hosted-fields.min.js" script in our <head> while also using this library. Must've forgotten to remove the script when bringing in the library.

**Comment by nathanstitt** [comment]
Oh that is interesting.  I'd never thought about that causing issues, I'll have to keep it in mind if I get other strange reports.  Glad you figured it out
