### ISSUE TITLE
should it work with react 18?

### ISSUE THREAD

**Issue by 3a1b2c3** [nathanstitt/react-braintree-fields#68]
should it work with react 18? getting no visible text fields

**Comment by nathanstitt** [comment]
Hi @3a1b2c3 it should work with React 18, but there was an incorrect version spec that only specified 16-17.  I've just released `v2.0.0` which will allow 18

**Comment by 3a1b2c3** [comment]
Awsome will try

**Comment by 3a1b2c3** [comment]
It works, still getting BraintreeError: Some payment input fields are invalid. Cannot tokenize invalid card fields. If i cannot figure whats wrong out  with my inputs  how will users? Is there a subscription option?

**Comment by 3a1b2c3** [comment]
![image](https://user-images.githubusercontent.com/74843139/219975992-6d43cf52-a0e3-44c4-82a8-24b4404797ec.png)
